[package]
name = "dfu-nusb"
version = "0.1.1"
edition = "2021"
authors = ["Sjoerd Simons <sjoerd@collabora.com>"]
license = "MIT OR Apache-2.0"
description = "Implementation of DFU using nusb and dfu-core"
homepage = "https://github.com/dfu-rs/dfu-nusb"
repository = "https://github.com/dfu-rs/dfu-nusb"
readme = "README.md"

[features]
default = ["tokio"]
tokio = ["dep:tokio", "nusb/tokio"]
smol = ["dep:smol", "nusb/smol"]

[dependencies]
dfu-core = { version = "0.11.0", features = ["async"] }
nusb = "0.2.3"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["time"], optional = true }
smol = {version="2.0.2", optional = true}

[dev-dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
futures = { version = "0.3.32", features = ["io-compat"] }
tokio = { version = "1.50.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["compat"] }
indicatif = { version = "0.18.4", features = [ "tokio" ] }
